version: "3.8"
services:
  file-portal:
    build: ./server
    container_name: file-portal
    environment:
      - PORT=8080
      - SESSION_SECRET=${SESSION_SECRET:-change-me-please}
      - AUTH_BCRYPT_HASH=${AUTH_BCRYPT_HASH}
      - MAX_UPLOAD_MB=${MAX_UPLOAD_MB:-200}
      - BASE_URL=${BASE_URL:-}
      - BRAND_TITLE=${BRAND_TITLE:-File Management}
      - DOWNLOAD_RATE_LIMIT_MAX=${DOWNLOAD_RATE_LIMIT_MAX:-60}
      - LINK_TTL_MS=${LINK_TTL_MS:-86400000}
      - TRUST_PROXY=${TRUST_PROXY:-1}
      - UPLOAD_CONCURRENCY=${UPLOAD_CONCURRENCY:-3}
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/sqlite:/app/sqlite
    ports:
      - "9876:8080"
    restart: unless-stopped
